-- Explicit Data API grants for every table in public.
--
-- Starting 2026-10-30 Supabase no longer auto-grants privileges on NEW tables in
-- public to anon / authenticated / service_role. Earlier migrations already
-- REVOKE everything from anon + authenticated and then GRANT authenticated only
-- what the app needs; those grants replay unchanged. What a fresh replay loses
-- is service_role's implicit access, which the Edge Functions (chat, memory,
-- redeem-plan) depend on. This migration restates the intended privilege set
-- so `supabase db reset`, local start, and preview branches behave like today.
--
-- Rules followed:
--   * anon gets nothing: every table was explicitly revoked from anon and the
--     browser only talks to tables after sign-in.
--   * authenticated grants mirror the existing migrations exactly (idempotent
--     restatement, nothing new, nothing that was revoked is re-granted).
--   * service_role gets only what the Edge Function code uses (it bypasses
--     RLS, so table grants are its only guard rail).
--   * No ALTER DEFAULT PRIVILEGES (see note at the end).
-- GRANT is idempotent; re-running this file is safe.

-- profiles: RLS on, select/update-own policies. Row is created by the
-- security-definer trigger private.handle_new_user, so no client INSERT/DELETE.
-- chat Edge Function reads custom_instructions via service_role.
grant select, update on table public.profiles to authenticated;
grant select on table public.profiles to service_role;

-- conversations: RLS on, full CRUD-own policies used by src/hooks/useChat.ts.
-- service_role needs select+update because its INSERT into messages fires the
-- (security invoker) trigger private.touch_conversation, which runs
-- `update public.conversations ... where id = ... and user_id = ...`.
grant select, insert, update, delete on table public.conversations to authenticated;
grant select, update on table public.conversations to service_role;

-- messages: RLS on, full CRUD-own policies used by useChat.ts.
-- chat Edge Function inserts the assistant reply via service_role and reads
-- back the id (.select('id')).
grant select, insert, update, delete on table public.messages to authenticated;
grant select, insert on table public.messages to service_role;

-- message_attachments: RLS on, select/insert/delete-own policies (no update).
-- Only touched through the user's JWT (browser + chat userClient).
grant select, insert, delete on table public.message_attachments to authenticated;

-- memories: RLS on, select/delete-own policies only. Clients cannot insert;
-- the memory Edge Function inserts via service_role and reads the row back.
grant select, delete on table public.memories to authenticated;
grant select, insert on table public.memories to service_role;

-- user_plans: RLS on, select-own policy for authenticated (usePlan.ts).
-- chat Edge Function reads the plan and flips status to 'expired' via
-- service_role. Writes on redemption happen inside the security-definer
-- function public.redeem_lunamax_code (runs as its owner, not service_role).
grant select on table public.user_plans to authenticated;
grant select, update on table public.user_plans to service_role;

-- chat_generations: RLS on, select-own policy for authenticated (polling in
-- useChat.ts). All writes come from the chat Edge Function via service_role.
grant select on table public.chat_generations to authenticated;
grant select, insert, update on table public.chat_generations to service_role;

-- rate_limits: RLS on, deny-all policy for authenticated; intentionally NO
-- client grants (initial_schema revoke + harden_schema deny policy).
-- chat/memory Edge Functions count, insert and prune rows via service_role.
grant select, insert, delete on table public.rate_limits to service_role;
grant usage on sequence public.rate_limits_id_seq to service_role;

-- usage_events: RLS on, deny-all policy for authenticated; NO client grants.
-- chat Edge Function reads daily cost and inserts events via service_role.
grant select, insert on table public.usage_events to service_role;
grant usage on sequence public.usage_events_id_seq to service_role;

-- plan_codes / plan_redemptions: RLS on, deny-all policies; NO grants to any
-- API role. They are only accessed inside public.redeem_lunamax_code
-- (security definer, EXECUTE granted to service_role only) and codes are
-- inserted by hand in the SQL Editor (scripts/generate-lunamax-code.mjs).
-- Intentionally nothing granted here.

-- Note on sequences: rate_limits, usage_events and plan_redemptions use
-- `generated by default as identity`. Identity defaults do not require
-- sequence privileges in Postgres; the USAGE grants above are belt-and-braces
-- for the two tables service_role inserts into. plan_redemptions_id_seq stays
-- ungranted (only the security-definer function inserts there).

-- Note on ALTER DEFAULT PRIVILEGES: deliberately not added. Recreating a
-- blanket default grant would undo the point of the platform change, and this
-- schema already follows a "revoke all, then grant explicitly" pattern per
-- table. Future migrations that create tables should include their own GRANTs.
